package com.footpath.store.model.enums;

public enum ResponseType {
	
	REGISTERED_ACTIVATED, REGISTERED_NOT_ACTIVATED, REGISTERED_DISABLED,
	
	VERIFICATION_TOKEN_INVALID, VERIFICATION_TOKEN_EXPIRED, 
	
	FEATURE_NOT_AVAILABLE,

}
